<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>panier</title>
</head>
<body>
    <div class="container">




    
            <form action="chariot.php" method="post">
            <div class="form-group">
            <h3 class="jombostron">vous avez commandé</h3>     
            vous êtes: 
            <input type="number" name="cid" class="form-control" ></br>        
            nom du produit: 
            <input type="number" name="pid" class="form-control" ></br>               
            quantité 
            <input type="number" name="qte" class="form-control" id="qte" placeholder="1" required></br> 
            prix toatale
            <div class="alert alert-success alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" > &times;</a>
            </div>
            statut delevry</br> 
            <input type="number" name="statut" id="" class="form-control"></input></br>
            <button type="submit" name="" class="btn btn-outline-success">confirm order</button> 
            </br>
            <button type="reset" class="btn btn-outline-danger" ><a href="">annuler</a></button> </br>
            </div>
            </form>
    </div>
</body>
</html>